### ISSUE TITLE
Problemas no envio gerados pelo Logo

### ISSUE THREAD

**Issue by chicocvenancio** [odoo-brazil/odoo-brazil-eletronic-documents#34]
Ao tentar realizar o envio da NFE as exceções de manipulação da imagem do logo geram o estado "Erro de autorização da Receita" sem explicações. No log é possível perceber a origem.

Encontrado no envio sem logotipo configurado e com imagem de logotipo que possui canal alpha.

**Comment by ztbucardi** [comment]
Bom dia doutor, 
Também tive esse problema, inclusive cheguei comentar com o Danimar e o Mackilem e eles me instruíram reinstalar a lib pillow.
Bem, a principio não deu certo mais vi que no meu caso tinha uma outra lib conflitando com ela, uma tal de PIL.
Removi as duas e instalei apenas a pillow e funcionou. Tenta isso, provavelmente funcione !

**Comment by chicocvenancio** [comment]
Boa noite, 
<s>Bem, como retirar o PIL? Ele não é necessário para o odoo?</s>

**Comment by danimaribeiro** [comment]
sudo pip uninstall PIL
sudo pip install pillow
Após a instalação ele geralmente da um resumo, tem que aparecer: "JPEG support available" e "PNG support available"

Por enquanto essa é a solução, mas o ideal seria que isso não interferisse no processo de envio da NF-e.

**Comment by ztbucardi** [comment]
E pelo que vi (entendi) por ai o pillow na verdade é uma especie de fork mesmo do PIL, veio para substitui-lo .... logo deve implementar todas funções do PIL, bem é o que entendi que o pessoal dos founs pythons da vida ai dizer .... 

De qualquer forma, nesse processo ai que o Danimar mostrou pelo menos aqui funfou !

**Comment by chicocvenancio** [comment]
Pois é, por isso que risquei ali em cima. Mas eu tive um problema devido ao python-pil do apt-get ser um pacote necessário para outro do sistema aqui. Resolvi criando um pacote vazio com o equivs que "provem" o python-pil.

**Comment by danimaribeiro** [comment]
O seguinte erro ocorre quando não está configurada a logo:     

```
 File "/home/trustcode/odoo/eletronic-docs/nfe/account_invoice.py", line 145, in action_invoice_send_nfe
for processo in send(company, nfe):
  File "/home/trustcode/odoo/eletronic-docs/nfe/sped/nfe/processing/xml.py", line 93, in send
p.danfe.logo = add_backgound_to_logo_image(company)
  File "/home/trustcode/odoo/eletronic-docs/nfe/sped/nfe/processing/xml.py", line 174, in add_backgound_to_logo_image
logo_image = Image.open(StringIO(logo.decode('base64')))
AttributeError: 'NoneType' object has no attribute 'decode'
```

O código atual ainda lança exceção em alguns casos, acho necessário não deixar que problemas com a logo impeça a emissão da nf-e.

```
 Traceback (most recent call last):
  File "/home/trustcode/odoo/eletronic-docs/nfe/account_invoice.py", line 145, in action_invoice_send_nfe
for processo in send(company, nfe):
  File "/home/trustcode/odoo/eletronic-docs/nfe/sped/nfe/processing/xml.py", line 93, in send
p.danfe.logo = add_backgound_to_logo_image(company)
   File "/home/trustcode/odoo/eletronic-docs/nfe/sped/nfe/processing/xml.py", line 178, in add_backgound_to_logo_image
bg.paste(logo_image, logo_image)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1126, in paste
self.im.paste(im, box, mask.im)
 ValueError: bad transparency mask
```

**Comment by christiandev** [comment]
Não esquecer de verificar se a JPEG runtime library está instalada no sistema:

**apt-cache search libjpeg-dev**

se não estiver instalada:

**sudo apt-get install libjpeg-dev**

depois reinstale o pillow:

**sudo -H pip install --no-cache-dir -I pillow**
