### ISSUE TITLE
Erro UnicodeDecode ao executar Manifesto destinatário

### ISSUE THREAD

**Issue by chicocvenancio** [odoo-brazil/odoo-brazil-eletronic-documents#37]
Recentemente percebi que uma de nossas instâncias não estava executando adequadamente o manifesto destinatário. Observando o log vejo o seguinte erro repetido a cada hora ou na execução manual do MDE.

2015-07-31 20:01:11,976 8740 ERROR VM_TECH openerp.addons.nfe_mde.nfe_schedule: 'ascii' codec can't decode byte 0xc3 in position 2687: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/nfe_mde/nfe_schedule.py", line 40, in schedule_download
    nfe_result = distribuicao_nfe(company, company.last_nsu_nfe)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/nfe_mde/service/mde.py", line 77, in distribuicao_nfe
    arq.write(orig_file_cont.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2687: ordinal not in range(128)

**Comment by chicocvenancio** [comment]
Aparentemente o orig_file.cont já está em utf-8, a tentativa de encodá-lo novamente gera o erro. 
Corrigi aqui retirando o .encode('utf-8') da linha 77 no mde.py. mais tarde passo um PR.

**Comment by danimaribeiro** [comment]
Alguma novidade?
