### ISSUE TITLE
Cadastro de terceiros / Consultar cadastro SEFAZ

### ISSUE THREAD

**Issue by Mackilem** [odoo-brazil/odoo-brazil-eletronic-documents#6]
Boa Tarde,

Após o cadastro do cliente (testei um do RS e outro de SC) tentei usar o botão (Consultar cadastro SEFAZ) e apresentou o seguinte erro, abaixo:

Server Traceback (most recent call last):
  File "/opt/openerp/web/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/nfe/nfe/res_partner.py", line 50, in sefaz_check
    processo = check_partner(company, cnpj_cpf, estato, ie)
  File "/opt/openerp/nfe/nfe/sped/nfe/processing/xml.py", line 66, in check_partner
    return  p.consultar_cadastro(estado, ie, cnpj_cpf)
  File "/usr/local/lib/python2.7/dist-packages/pysped/nfe/processador_nfe.py", line 1317, in consultar_cadastro
    self._conectar_servico(WS_NFE_CONSULTA_CADASTRO, envio, resposta, 1)
  File "/usr/local/lib/python2.7/dist-packages/pysped/nfe/processador_nfe.py", line 212, in _conectar_servico
    if type(webservices_2.ESTADO_WS[self.estado][ambiente][servico]) == dict:
KeyError: 6

**Comment by danimaribeiro** [comment]
O erro vai ocorrer em todos os estados que utilizam o sefaz do RS ou o sefaz Virtual.

O componente pysped gera a url de consulta apartir de um padrão servidor/caminhorelativo, ele usa o mesmo padrão para todas os métodos, porém nos webservices do RS o webservice de consulta usa um servidor diferente:

Exemplos:
https://homologacao.nfe.sefaz.rs.gov.br/ws/Nferecepcao/NFeRecepcao2.asmx  https://homologacao.nfe.sefaz.rs.gov.br/ws/nfeDownloadNF/nfeDownloadNF.asmx   https://sef.sefaz.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx  - Url fora do padrão.

Necessita de uma mudança significativa no componente pysped.

**Comment by danimaribeiro** [comment]
Corrigido no PySPED.

**Comment by chicocvenancio** [comment]
Esse bug foi corrigido mesmo?
Estou recebendo ele nos casos dos Estados que usam o servidor virtual.

**Comment by danimaribeiro** [comment]
Esta usando qual branch do pysped, e quais estados que está ocorrendo?

**Comment by chicocvenancio** [comment]
Está ocorrendo no Maranhão ao menos.

**Comment by danimaribeiro** [comment]
Consegue me passar dados para teste? Um cnpj válido de lá.

**Comment by chicocvenancio** [comment]
Serve o do Estado?
06.354.468/0001-60

Chico Venancio
CEO e Diretor de Criação
VM TECH - (98) 9 8800 2743

2015-06-13 18:16 GMT-03:00 Danimar Ribeiro notifications@github.com:

**Comment by danimaribeiro** [comment]
Realmente o erro ocorre no maranhão.

**Comment by danimaribeiro** [comment]
Infelizmente mesmo corrigindo a url do estado do Maranhão parece que o webservice de consulta não está de acordo com os outros.
Recebo o erro de que o certificado não foi enviado, apesar de estar sendo enviado:
HTTP Status 400 - No client certificate chain in this request

**Comment by mileo** [comment]
Pode ser que ele seja como o de GO; 

Que vc precisa enviar a cadeia completa + o certificado da empresa. 

Te explico melhor isso qualquer hora. 

[]s 

## 

Luis Felipe Miléo 
KMEE 
+55 35 8876-3663 
+55 35 3622-2548 
skype: luisfelipemileo 
mileo@kmee.com.br 
kmee.com.br 
Parceiro oficial no Brasil: 

De: "Danimar Ribeiro" notifications@github.com 
Para: "odoo-brazil/odoo-brazil-eletronic-documents" odoo-brazil-eletronic-documents@noreply.github.com 
Enviadas: Sábado, 13 de junho de 2015 19:45:53 
Assunto: Re: [odoo-brazil-eletronic-documents] Cadastro de terceiros / Consultar cadastro SEFAZ (#6) 

Infelizmente mesmo corrigindo a url do estado do Maranhão parece que o webservice de consulta não está de acordo com os outros. 
Recebo o erro de que o certificado não foi enviado, apesar de estar sendo enviado: 
HTTP Status 400 - No client certificate chain in this request

**Comment by ghost** [comment]
Erro ao se comunicar com o SEFAZ

0 - None

Alguma ajuda?

**Comment by andreramoslj** [comment]
Alguém já descobriu a solução para esse problema? Não consigo fazer a comunicação para os estados que utilizam o SVRS. (Com exceçao de  AC, RN, PB, SC).
Por exemplo, quando eu troco a sigla do estado no xml para RJ, ele diz que "Sigla da UF Da consulta difere da UF do WebService"

Qual url usar para os estados que não tem endereço no sefaz?

ps: Já tentei usar com essas e não deu certo:
https://sef.sefaz.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx 
https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx
https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro2.asmx
